[project]
name = "tx0-lab"
version = "0.1.0"
description = "Lab setup for Concourse"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pyinfra>=3.3.1"]

[tool.basedpyright]
reportUnknownVariableType = false
reportUnknownMemberType = false
